select * from tabs;
select * from QUIZE_SCORE;

SELECT NM , 
MIN(SCORE) ||  '~' ||  (MAX(SCORE)) as SCORE_RAG,
count(nm) as 건수, count(DISTINCT SCORE) as 중복1건처리
from QUIZE_SCORE 
GROUP BY NM
HAVING count(DISTINCT SCORE) >= 2; 


select * from STD_SCORE;
select * from COURSE_CREDITS;


select NM, SUBJECT, SCORE, GRADE, ST_RNG, ET_RNG from STD_SCORE, COURSE_CREDITS
where SCORE BETWEEN ST_RNG and ET_RNG
order by nm;


-- 3.1  SQL 함수활용 1
select RPAD('A',3,'BCDEFGHIZKLMNOPQRSTUVWXYZ') from DUAL;

SELECT RNUM SEQ
, LPAD('*', RNUM, '*') T1 
, LPAD('A',RNUM, 'B') T2
, DECODE (SIGN(RNUM-5), 1, 6-((RNUM -4)), RNUM) AS DSEQ
, LPAD('*',DECODE(SIGN(RNUM-5),1,6-((RNUM-4)),RNUM),'*') DFTST
, CASE WHEN RNUM -5 >= 1 THEN ((RNUM -4))  ELSE RNUM  END AS CSEQ
, LPAD('*', CASE WHEN RNUM -5 >= 1 THEN 6-((RNUM -4)) ELSE RNUM END , '*')  CFTST
, 'A' || F_GET_ALPA('B', RNUM) T4
FROM (SELECT ROWNUM RNUM FROM USER_TAB_COLUMNS WHERE ROWNUM < 10 ORDER BY RNUM ASC);

-- 3.1  SQL 함수활용 2
SELECT RNUM SEQ 
, LPAD('*', RNUM, '#') T1
, LPAD('A', RNUM, 'B') T2
, DECODE (SIGN(RNUM-10), 1, 11-((RNUM-9)), RNUM) AS DSEQ
, LPAD('*', DECODE(SIGN(RNUM-10), 1, 11-((RNUM-9)),RNUM), '*') DETST 
, CASE WHEN RNUM -10 >= 1 THEN 11- ((RNUM-9)) ELSE RNUM END AS CESQ
, LPAD('*', CASE WHEN RNUM -10 >= 1 THEN 11- ((RNUM-9)) ELSE RNUM END, '*') AS CFTST
, 'A' || F_GET_ALPA('B',RNUM) T4
FROM (SELECT ROWNUM RNUM FROM USER_TAB_COLUMNS WHERE ROWNUM < 20 ORDER BY RNUM ASC);


SELECT * from ALL_TAB_COLUMNS;
SELECT * FROM :INP_VAL;
SELECT * FROM :RVS_PT;


-- 3.1  SQL 함수활용 3
SELECT RNUM SEQ
, LPAD('*', RNUM, '*') T1
, LPAD('A',RNUM, 'B') T2
, DECODE(SIGN(RNUM-RVS_PT), 1, (RVS_PT)+1 -(RNUM-(RVS_PT-1)), RNUM) AS DSEQ
, LPAD('*', DECODE(SIGN(RNUM-RVS_PT),1,(RVS_PT)+1-(RNUM-(RVS_PT-1)),RNUM),'*') DFTST
, CASE WHEN RNUM -RVS_PT >= 1 THEN (RVS_PT)+1 -(RNUM-(RVS_PT-1))
   ELSE RNUM
   END AS CSEQ
, LPAD('*', CASE WHEN RNUM -RVS_PT >= 1 THEN (RVS_PT)+1 -(RNUM-(RVS_PT-1))
   ELSE RNUM
   END
   , '*') CFTST
, 'A' || DECODE(RNUM, 1, NULL, F_GET_ALPA('B', RNUM-1)) T4
FROM (
	SELECT ROWNUM RNUM
   , CASE WHEN MOD(ROWNUM,2) = 1 THEN  ROUND((ROWNUM/2),0)  END AS RVS_PT
   , CASE WHEN MOD(ROWNUM,2) = 0 THEN ((ROWNUM/2) + 1) END AS RVS_PT
   FROM ALL_TAB_COLUMNS
	WHERE ROWNUM < 20 
	ORDER BY RNUM ASC
);

RVS_PT ; 
MOD(RNUM,2) 일때 나머지가 1인경우, RVS_PT=ROUND((RNUM /2),0)
MOD(RNUM,2) 일때 나머지가 0인경우,  RVS_PT=RNUM / 2


INP_VAL ; 
20의 값을 어떻게 넣어줄 것인가?




