




SELECT NM, REGION_AREA
	, COL0 || '( ' || TO_CHAR(ROUND((COL0/TOT*100),2), 'FM990.0' )  || ' %)' -- 이 형태로 맞춤 
			  || DECODE(COL0, GREATEST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),  '▲'
			  							, LEAST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9), '▼')    	
			 || '*' || RR_COL
			   		A					
			  							
	, COL1 || '( ' || TO_CHAR(ROUND((COL1/TOT*100),2), 'FM990.0' )  || ' %)'
			  || DECODE(COL1, GREATEST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),  '▲'
			  							, LEAST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9), '▼')      
			  							
			   || '*' 
			 		B				
			  							
	, COL2 || '( ' || TO_CHAR(ROUND((COL2/TOT*100),2), 'FM990.0' )  || ' %)'
			  || DECODE(COL2, GREATEST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),  '▲'
			  							, LEAST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9), '▼')      C
			  							
	, COL3 || '( ' || TO_CHAR(ROUND((COL3/TOT*100),2), 'FM990.0' )  || ' %)'
			  || DECODE(COL3, GREATEST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),  '▲'
			  						,	 LEAST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9), '▼')      D
			  							
	, COL4 || '( ' || TO_CHAR(ROUND((COL4/TOT*100),2), 'FM990.0' )  || ' %)'
			  || DECODE(COL4, GREATEST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),  '▲'
			  							,  LEAST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9), '▼')       E
			  							
	, COL5 || '( ' || TO_CHAR(ROUND((COL5/TOT*100),2), 'FM990.0' )  || ' %)'
			  || DECODE(COL5, GREATEST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),  '▲'
			  							, LEAST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9), '▼')       F
			  							
	, COL6 || '( ' || TO_CHAR(ROUND((COL6/TOT*100),2), 'FM990.0' )  || ' %)'
			  || DECODE(COL6, GREATEST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),  '▲'
			  							,  LEAST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9), '▼')       G
			  							
	, COL7 || '( ' || TO_CHAR(ROUND((COL7/TOT*100),2), 'FM990.0' )  || ' %)'
			  || DECODE(COL7, GREATEST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),  '▲'
			  							, LEAST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9), '▼', '')      H
			  							
	, COL8 || '( ' || TO_CHAR(ROUND((COL8/TOT*100),2), 'FM990.0' )  || ' %)'
			  || DECODE(COL8, GREATEST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),  '▲'
			  							, LEAST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9), '▼', '')      I
			  							
	, COL9 || '( ' || TO_CHAR(ROUND((COL9/TOT*100),2), 'FM990.0' )  || ' %)'
			  || DECODE(COL9, GREATEST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),  '▲'
			  							, LEAST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9), '▼', '')      J
	
	, TOT 					
			  							
FROM 
(
SELECT AREA_CD
      ,DECODE(GROUPING(AREA_CD)||GROUPING(REGION_AREA),'00',MIN(CD_NM)
                  ,'01',MIN(CD_NM)||'합계','총계') NM
      ,REGION_AREA   
      ,NVL(  SUM(DECODE(PROD_ID,'100000',SALE_CNT)) , 0) COL0
      ,NVL(  SUM(DECODE(PROD_ID,'100001',SALE_CNT)) , 0)  COL1
      ,NVL(  SUM(DECODE(PROD_ID,'100002',SALE_CNT)) , 0) COL2
      ,NVL(  SUM(DECODE(PROD_ID,'100003',SALE_CNT)) , 0) COL3
      ,NVL(  SUM(DECODE(PROD_ID,'100004',SALE_CNT)) , 0) COL4
      ,NVL(  SUM(DECODE(PROD_ID,'100005',SALE_CNT)) , 0) COL5
      ,NVL(  SUM(DECODE(PROD_ID,'100006',SALE_CNT)) , 0) COL6
      ,NVL(  SUM(DECODE(PROD_ID,'100007',SALE_CNT)) , 0) COL7
      ,NVL(  SUM(DECODE(PROD_ID,'100008',SALE_CNT)) , 0) COL8
      ,NVL(  SUM(DECODE(PROD_ID,'100009',SALE_CNT)) , 0) COL9
      ,SUM(SALE_CNT) TOT
      ,GROUPING(AREA_CD)||GROUPING(REGION_AREA) GR
FROM(    
  SELECT AREA_CD
          ,REGION_AREA
          ,PROD_ID
          ,SUM(SALE_CNT) SALE_CNT
          , RANK() OVER(PARTITION BY AREA_CD, REGION_AREA ORDER BY SUM(SALE_CNT)  DESC ) RR_COL
    FROM SALE_TBL    
    GROUP BY AREA_CD
            ,REGION_AREA 
            ,PROD_ID
  )
TA, CD_TBL TB  
WHERE TA.AREA_CD = TB.CD_ID
GROUP BY ROLLUP(AREA_CD ,REGION_AREA)
ORDER BY 1,2   

)
;






  SELECT AREA_CD
          ,REGION_AREA
          ,PROD_ID
          ,SUM(SALE_CNT) SALE_CNT
          , RANK() OVER(PARTITION BY AREA_CD, REGION_AREA ORDER BY SUM(SALE_CNT)  DESC )  RR_COL
    FROM SALE_TBL    
    GROUP BY AREA_CD
            ,REGION_AREA 
            ,PROD_ID
               ;



-- 소스 확인하기 


SELECT NM, REGION_AREA
	, COL0 || '( ' || TO_CHAR(ROUND((COL0/TOT*100),2), 'FM990.0' )  || ' %)' -- 이 형태로 맞춤 
			  || DECODE(COL0, GREATEST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),  '▲'
			  							, LEAST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9), '▼')   ||  R0   청소기
			  							
	, COL1 || '( ' || TO_CHAR(ROUND((COL1/TOT*100),2), 'FM990.0' )  || ' %)'
			  || DECODE(COL1, GREATEST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),  '▲'
			  							, LEAST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9), '▼')  ||    R1        세탁기
			  							
	, COL2 || '( ' || TO_CHAR(ROUND((COL2/TOT*100),2), 'FM990.0' )  || ' %)'
			  || DECODE(COL2, GREATEST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),  '▲'
			  							, LEAST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9), '▼')   ||    R2      건조기
			  							
	, COL3 || '( ' || TO_CHAR(ROUND((COL3/TOT*100),2), 'FM990.0' )  || ' %)'
			  || DECODE(COL3, GREATEST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),  '▲'
			  							,LEAST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9), '▼')  ||     R3        정수기
			  							
	, COL4 || '( ' || TO_CHAR(ROUND((COL4/TOT*100),2), 'FM990.0' )  || ' %)'
			  || DECODE(COL4, GREATEST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),  '▲'
			  							, LEAST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9), '▼')  ||    R4         도어락
			  							
	, COL5 || '( ' || TO_CHAR(ROUND((COL5/TOT*100),2), 'FM990.0' )  || ' %)'
			  || DECODE(COL5, GREATEST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),  '▲'
			  							, LEAST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9), '▼')   ||     R5        전화기
			  							
	, COL6 || '( ' || TO_CHAR(ROUND((COL6/TOT*100),2), 'FM990.0' )  || ' %)'
			  || DECODE(COL6, GREATEST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),  '▲'
			  							, LEAST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9), '▼')    ||    R6        냉장고
			  							
	, COL7 || '( ' || TO_CHAR(ROUND((COL7/TOT*100),2), 'FM990.0' )  || ' %)'
			  || DECODE(COL7, GREATEST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),  '▲'
			  							, LEAST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9), '▼')    ||   R7        김치냉장고
			  							
	, COL8 || '( ' || TO_CHAR(ROUND((COL8/TOT*100),2), 'FM990.0' )  || ' %)'
			  || DECODE(COL8, GREATEST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),  '▲'
			  							, LEAST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9), '▼')    ||    R8        전자레인지
			  							
	, COL9 || '( ' || TO_CHAR(ROUND((COL9/TOT*100),2), 'FM990.0' )  || ' %)'
			  || DECODE(COL9, GREATEST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),  '▲'
			  							, LEAST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9), '▼')   ||     R9       가스레인지
			|| DECODE(GR, '00', '*' || NVL(R9, MXRR)) 
	, TOT 					
			  							
FROM 
(
SELECT AREA_CD
      ,DECODE(GROUPING(AREA_CD)||GROUPING(REGION_AREA),'00',MIN(CD_NM)
                  ,'01',MIN(CD_NM)||'합계','총계') NM
      ,REGION_AREA  
      
      ,  MIN(DECODE(PROD_ID,'100000', RR_COL))) R0
      ,  DECODE(GROUPING(AREA_CD)||GROUPING(REGION_AREA),'00',MIN(DECODE(PROD_ID, '100001', RR_COL))) R1
      ,  DECODE(GROUPING(AREA_CD)||GROUPING(REGION_AREA),'00',MIN(DECODE(PROD_ID,'100002', RR_COL))) R2
      ,  DECODE(GROUPING(AREA_CD)||GROUPING(REGION_AREA),'00',MIN(DECODE(PROD_ID, '100003', RR_COL))) R3
      ,  DECODE(GROUPING(AREA_CD)||GROUPING(REGION_AREA),'00',MIN(DECODE(PROD_ID, '100004', RR_COL))) R4
      ,  DECODE(GROUPING(AREA_CD)||GROUPING(REGION_AREA),'00',MIN(DECODE(PROD_ID, '100005', RR_COL))) R5
      ,  DECODE(GROUPING(AREA_CD)||GROUPING(REGION_AREA),'00',MIN(DECODE(PROD_ID, '100006', RR_COL))) R6
      ,  DECODE(GROUPING(AREA_CD)||GROUPING(REGION_AREA),'00',MIN(DECODE(PROD_ID, '100007', RR_COL))) R7
      ,  DECODE(GROUPING(AREA_CD)||GROUPING(REGION_AREA),'00',MIN(DECODE(PROD_ID, '100008', RR_COL))) R8
      ,  DECODE(GROUPING(AREA_CD)||GROUPING(REGION_AREA),'00',MIN(DECODE(PROD_ID, '100009', RR_COL))) R9
      , MAX(RR_COL) +1 MXRR
      ,NVL(  SUM(DECODE(PROD_ID,'100000',SALE_CNT)) , 0)  COL0
      ,NVL(  SUM(DECODE(PROD_ID,'100001',SALE_CNT)) , 0)  COL1
      ,NVL(  SUM(DECODE(PROD_ID,'100002',SALE_CNT)) , 0) COL2
      ,NVL(  SUM(DECODE(PROD_ID,'100003',SALE_CNT)) , 0) COL3
      ,NVL(  SUM(DECODE(PROD_ID,'100004',SALE_CNT)) , 0) COL4
      ,NVL(  SUM(DECODE(PROD_ID,'100005',SALE_CNT)) , 0) COL5
      ,NVL(  SUM(DECODE(PROD_ID,'100006',SALE_CNT)) , 0) COL6
      ,NVL(  SUM(DECODE(PROD_ID,'100007',SALE_CNT)) , 0) COL7
      ,NVL(  SUM(DECODE(PROD_ID,'100008',SALE_CNT)) , 0) COL8
      ,NVL(  SUM(DECODE(PROD_ID,'100009',SALE_CNT)) , 0) COL9
      ,SUM(SALE_CNT) TOT
      ,GROUPING(AREA_CD)||GROUPING(REGION_AREA) GR
      
FROM(    
  SELECT AREA_CD
          ,REGION_AREA
          ,PROD_ID
          ,SUM(SALE_CNT) SALE_CNT
          , RANK() OVER(PARTITION BY AREA_CD, REGION_AREA ORDER BY SUM(SALE_CNT)  DESC ) RR_COL
    FROM SALE_TBL    
    GROUP BY AREA_CD
            ,REGION_AREA 
            ,PROD_ID
  )
TA, CD_TBL TB  
WHERE TA.AREA_CD = TB.CD_ID
GROUP BY ROLLUP(AREA_CD ,REGION_AREA)
ORDER BY 1,2   
)  
;









SELECT AREA_CD
          ,REGION_AREA
          ,PROD_ID
          ,SUM(SALE_CNT) SALE_CNT
          , RANK() OVER(PARTITION BY AREA_CD, REGION_AREA ORDER BY SUM(SALE_CNT)  DESC ) RR_COL
    FROM SALE_TBL    
    GROUP BY AREA_CD
            ,REGION_AREA 
            ,PROD_ID;
