

CREATE TABLE USERS (

   USERID   VARCHAR2(20)  NOT NULL PRIMARY KEY,
   NAME     VARCHAR2(100) NOT NULL,
   GENDER  VARCHAR2(10),
   CITY  VARCHAR2(30)
);

SELECT * FROM USERS;

INSERT INTO USERS VALUES(
'gildong','홍길동','남','서울'
);

COMMIT