
-- 분석함수의 이해 (WINDOW 활용)


SELECT* FROM STUDENT;
-- CASE1. ROWS BETWEEN 1 PRECEDING AND CURRENT ROW

SELECT DEPTNO
	   ,	  STUDNO
	   ,	  WEIGHT
	   ,  BIRTHDATE
	   ,  MONTH_TST
	   ,  FIRST_VALUE(WEIGHT) OVER(PARTITION BY DEPTNO ORDER BY STUDNO ROWS BETWEEN 1 PRECEDING AND CURRENT ROW) FSTR_WEIGHT_SUM_NB
	   ,  LAST_VALUE(WEIGHT) OVER(PARTITION BY DEPTNO ORDER BY STUDNO ROWS BETWEEN 1 PRECEDING AND CURRENT ROW) LSTR_WEIGHT_SUM_NB
	   ,  SUM(WEIGHT) OVER(PARTITION BY DEPTNO ORDER BY STUDNO ROWS BETWEEN 1 PRECEDING AND CURRENT ROW) AS WEIGHT_SUM_NB
FROM STUDENT 
ORDER BY DEPTNO1;


SELECT * FROM STUDENT;


-- CASE2. ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
SELECT  DEPTNO
	, STUDNO
	, WEIGHT
	, BIRTHDATE
	, MONTH_TST
	, FIRST_VALUE(WEIGHT) OVER(PARTITION BY DEPTNO ORDER BY STUDNO ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) FSTR_WEIGHT_SUM_UB
	, LAST_VALUE(WEIGHT) OVER(PARTITION BY DEPTNO ORDER BY STUDNO ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) LSTR_WEIGHT_SUM_UB
	, SUM(WEIGHT) OVER(PARTITION BY DEPTNO ORDER BY STUDNO ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS WEIGHT_SUM_UB
FROM STUDENT
ORDER BY DEPTNO;


-- CASE3. ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
SELECT DEPTNO
	, STUDNO
	, WEIGHT
	, BIRTHDATE
	, MONTH_TST
	, FIRST_VALUE(WEIGHT) OVER(PARTITION BY DEPTNO ORDER BY STUDNO ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) FSTR_WEIGHT_SUM_UB
	, LAST_VALUE(WEIGHT) OVER(PARTITION BY DEPTNO ORDER BY STUDNO ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) LSTR_WEIGHT_SUM_UB
	, SUM(WEIGHT) OVER(PARTITION BY DEPTNO ORDER BY STUDNO ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS WEIGHT_SUM_UB_FB
FROM STUDENT
ORDER BY DEPTNO;


-- CASE4. RANGE BETWEEN 1 PRECEDING AND 2 FOLLOWING
SELECT DEPTNO
	, STUDNO
	, WEIGHT
	, BIRTHDATE
	, MONTH_TST
	, FIRST_VALUE(WEIGHT) OVER(PARTITION BY DEPTNO ORDER BY MONTH_TST RANGE BETWEEN 1 PRECEDING AND 2 FOLLOWING) FSTR_WEIGHT_SUM_UB
	, LAST_VALUE(WEIGHT) OVER(PARTITION BY DEPTNO ORDER BY MONTH_TST RANGE BETWEEN 1 PRECEDING AND 2 FOLLOWING) LSTR_WEIGHT_SUM_UB
	, SUM(WEIGHT) OVER(PARTITION BY DEPTNO ORDER BY MONTH_TST RANGE BETWEEN 1 PRECEDING AND 2 FOLLOWING) AS WEIGHT_SUM_UB_FB
FROM STUDENT
ORDER BY DEPTNO
;


-- CASE5. RANGE BETWEEN INTERVAL '2' YEAR PRECEDING AND INTERVAL '3' YEAR FOLLOWING
SELECT DEPTNO
	, STUDNO
	, WEIGHT
	, BITRHDATE
	, MONTH_TST
	, FIRST_VALUE(BIRTHDATE) OVER(PARTITION BY DEPTNO ORDER BY BIRTHDATE RANGE BETWEEN INTERVAL '2' YEAR PRECEDING AND INTERVAL '3' YEAR FOLLOWING) FSTR_WEIGHT_SUM_UB
	, LAST_VALUE(BIRTHDATE) OVER(PARTITION BY DEPTNO ORDER BY BIRTHDATE RANGE BETWEEN INTERVAL '2' YEAR PRECEDING AND INTERVAL '3' YEAR FOLLOWING) LSTR_WEIGHT_SUM_UB
	, SUM(WEIGHT)  OVER(PARTITION BY DEPTNO ORDER BY BIRTHDATE RANGE BETWEEN INTERVAL '2' YEAR PRECEDING AND INTERVAL '3' YEAR FOLLOWING ) WEIGHT_SUM_UB_FB
FROM STUDENT
ORDER BY DEPTNO;

