DESC V_DIA_HW1;

SELECT * FROM DIA_TBL;


CREATE TABLE DIA_TBL_COPY02 AS 
SELECT * FROM DIA_TBL;

COMMIT;
SELECT * FROM DIA_TBL_COPY01;
SELECT * FROM DIA_TBL_COPY02;

ALTER TABLE  DIA_TBL_COPY01 ADD (PNAME VARCHAR2(100));
ALTER TABLE DIA_TBL_COPY01 DROP  COLUMN PNAME ;




MERGE INTO DIA_TBL_COPY02 A   -- UPDATE 대상 TABLE 
USING DIA_TBL_COPY01 B   -- 비교테이블
ON (A.PID = B.NID ) 
WHEN MATCHED THEN 
UPDATE SET  PNAME = '관할부서 [' || B.NAME || '] '  
;






SELECT * FROM ORG_TBL;

SELECT MAX(NO) 번호
		, MIN(ST_DT) 시작날짜
		, MAX(ET_DT) 종료날짜
		, MAX(NM) 이름 
FROM 
(
SELECT NO, NM, ST_DT, ET_DT 
			,SUM(GR) OVER(PARTITION BY NO ORDER BY NO, ST_DT)  GR
FROM
(
SELECT NO, NM, ST_DT, ET_DT
		, LAG(ET_DT) OVER(PARTITION BY NO ORDER BY NO, ST_DT)  LET_DT
		, DECODE(ST_DT -  LAG(ET_DT) OVER(PARTITION BY NO ORDER BY NO, ST_DT), 0, 0, 1) GR
FROM ORG_TBL
)
)
GROUP BY NO, GR 
ORDER BY NO, MIN(ST_DT)
;

SELECT ROWNUM
		,  TO_CHAR(SYSDATE - ROWNUM, 'YYYY-MM-DD') 현재기준
FROM DUAL 
CONNECT BY LEVEL <= 5; 




SELECT * FROM AS_HIST;

SELECT * FROM TABS
ORDER BY TABLE_NAME;


 