

--WITH : 동일 테이블 반복 사용 시 사용
WITH WORK_BAS_TBL AS 
(
SELECT A.ACCNT 
	, A.BALNC 
	, B.ACCNT TRANS_ACCNT 
	, B.BALNC TRANS_BALNC
	, B.TRANS_RSN
FROM MASTER_TBL A, 
	 TRANS_TBL B 
WHERE A.ACCNT (+) = B.ACCNT 	
)
SELECT NVL(ACCNT, TRANS_ACCNT) ACCNT 
		 , NVL(
		 BALNC,0) + TRANS_BALNC BALNC 
		 , TRANS_RSN
FROM WORK_BAS_TBL 
WHERE TRANS_RSN IN ('입금', '신규계약')
UNION ALL 
SELECT NVL(ACCNT, TRANS_ACCNT) ACCNT 
	, 0 BALNC 
	, TRANS_RSN 
FROM WORK_BAS_TBL 
WHERE TRANS_RSN IN ('해지') 
;


SELECT * FROM CD_TBL;
SELECT * FROM SALE_TBL;

SELECT * FROM TABS;


DESC V_DIA_HW01;

SELECT NM, REGION_AREA
	, COL0 || '( ' || TO_CHAR(ROUND((COL0/TOT*100),2), 'FM90.0' )  || ' %)'
			  || DECODE(COL0, GREATEST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),  '▲'
			  							, LEAST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9), '▼', '')     청소기
			  							
	, COL1 || '( ' || TO_CHAR(ROUND((COL1/TOT*100),2), 'FM90.0' )  || ' %)'
			  || DECODE(COL1, GREATEST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),  '▲'
			  							, LEAST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9), '▼', '')      세탁기
			  							
	, COL2 || '( ' || TO_CHAR(ROUND((COL2/TOT*100),2), 'FM90.0' )  || ' %)'
			  || DECODE(COL2, GREATEST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),  '▲'
			  							, LEAST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9), '▼', '')      건조기
			  							
	, COL3 || '( ' || TO_CHAR(ROUND((COL3/TOT*100),2), 'FM90.0' )  || ' %)'
			  || DECODE(COL3, GREATEST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),  '▲'
			  							, LEAST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9), '▼', '')      정수기
			  							
	, COL4 || '( ' || TO_CHAR(ROUND((COL4/TOT*100),2), 'FM90.0' )  || ' %)'
			  || DECODE(COL4, GREATEST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),  '▲'
			  							, LEAST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9), '▼', '')      도어락
			  							
	, COL5 || '( ' || TO_CHAR(ROUND((COL5/TOT*100),2), 'FM90.0' )  || ' %)'
			  || DECODE(COL5, GREATEST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),  '▲'
			  							, LEAST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9), '▼', '')      전화기
			  							
	, COL6 || '( ' || TO_CHAR(ROUND((COL6/TOT*100),2), 'FM90.0' )  || ' %)'
			  || DECODE(COL6, GREATEST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),  '▲'
			  							, LEAST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9), '▼', '')      냉장고
			  							
	, COL7 || '( ' || TO_CHAR(ROUND((COL7/TOT*100),2), 'FM90.0' )  || ' %)'
			  || DECODE(COL7, GREATEST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),  '▲'
			  							, LEAST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9), '▼', '')      김치냉장고
			  							
	, COL8 || '( ' || TO_CHAR(ROUND((COL8/TOT*100),2), 'FM90.0' )  || ' %)'
			  || DECODE(COL8, GREATEST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),  '▲'
			  							, LEAST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9), '▼', '')      전자레인지
			  							
	, COL9 || '( ' || TO_CHAR(ROUND((COL9/TOT*100),2), 'FM90.0' )  || ' %)'
			  || DECODE(COL9, GREATEST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),  '▲'
			  							, LEAST(COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9), '▼', '')      가스레인지
	
	, TOT 					
			  							
FROM 
(

SELECT AREA_CD
      ,DECODE(GROUPING(AREA_CD)||GROUPING(REGION_AREA),'00',MIN(CD_NM)
                  ,'01',MIN(CD_NM)||'합계','총계') NM
      ,REGION_AREA
      ,NVL(  SUM(DECODE(PROD_ID,'100000',SALE_CNT)) , 0) COL0
      ,NVL(  SUM(DECODE(PROD_ID,'100001',SALE_CNT)) , 0)  COL1
      ,NVL(  SUM(DECODE(PROD_ID,'100002',SALE_CNT)) , 0) COL2
      ,NVL(  SUM(DECODE(PROD_ID,'100003',SALE_CNT)) , 0) COL3
      ,NVL(  SUM(DECODE(PROD_ID,'100004',SALE_CNT)) , 0) COL4
      ,NVL(  SUM(DECODE(PROD_ID,'100005',SALE_CNT)) , 0) COL5
      ,NVL(  SUM(DECODE(PROD_ID,'100006',SALE_CNT)) , 0) COL6
      ,NVL(  SUM(DECODE(PROD_ID,'100007',SALE_CNT)) , 0) COL7
      ,NVL(  SUM(DECODE(PROD_ID,'100008',SALE_CNT)) , 0) COL8
      ,NVL(  SUM(DECODE(PROD_ID,'100009',SALE_CNT)) , 0) COL9
      ,SUM(SALE_CNT) TOT
      ,GROUPING(AREA_CD)||GROUPING(REGION_AREA) GR
FROM(
    SELECT AREA_CD
          ,REGION_AREA
          ,PROD_ID
          ,SUM(SALE_CNT) SALE_CNT
    FROM SALE_TBL    
    GROUP BY AREA_CD
            ,REGION_AREA
            ,PROD_ID
)  
TA, CD_TBL TB  
WHERE TA.AREA_CD = TB.CD_ID
GROUP BY ROLLUP(AREA_CD ,REGION_AREA)
ORDER BY 1,2
)   
;



SELECT 
    	NVL(SUM(DECODE(PROD_ID , '100000', SALE_CNT)),0) NM0
	,	NVL(SUM(DECODE(PROD_ID , '100001', SALE_CNT)),0) NM1
	,	NVL(SUM(DECODE(PROD_ID , '100002', SALE_CNT)),0) NM2
	,	NVL(SUM(DECODE(PROD_ID , '100003', SALE_CNT)),0) NM3
	,	NVL(SUM(DECODE(PROD_ID , '100004', SALE_CNT)),0) NM4
	,	NVL(SUM(DECODE(PROD_ID , '100005', SALE_CNT)),0) NM5
	,	NVL(SUM(DECODE(PROD_ID , '100006', SALE_CNT)),0) NM6
	,	NVL(SUM(DECODE(PROD_ID , '100007', SALE_CNT)),0) NM7
	,	NVL(SUM(DECODE(PROD_ID , '100008', SALE_CNT)),0) NM8
	,	NVL(SUM(DECODE(PROD_ID , '100009', SALE_CNT)),0) NM9
	
FROM
(
SELECT AREA_CD
          ,REGION_AREA
          ,PROD_ID
          ,SUM(SALE_CNT) SALE_CNT
FROM SALE_TBL    
--WHERE PROD_ID = '100000'
GROUP BY AREA_CD
            ,REGION_AREA
            ,PROD_ID 
)
;





SELECT 
	LTRIM(MAX(SYS_CONNECT_BY_PATH(NID, '+')),'+') || '=' || SUM(NID)  CALCU
FROM
(
SELECT 
	ROWNUM + :ST -1 NID 
	, ROWNUM + :ST PID 
FROM DUAL 
CONNECT BY LEVEL <= :ET - :ST + 1 
)
CONNECT BY PRIOR DECODE(:AA, 'A', NID, PID)  = DECODE(:AA,'A',PID,NID)  
START WITH NID = DECODE(:AA,'A', :ET, :ST) 
;




	
SELECT * FROM MASTER_TBL;
SELECT * FROM TRANS_TBL;



























 
