CREATE OR REPLACE PROCEDURE PROC_TST
IS 
	L_DNAME  DEPT.DNAME%TYPE;
	DEPT_REC1 DEPT%ROWTYPE;
	
	CURSOR C1 IS 
	SELECT DEPTNO, DNAME
	FROM DEPT;
	
	DEPT_REC2 C1%ROWTYPE;
	
BEGIN

	SELECT * 
		INTO DEPT_REC1 
	FROM DEPT
	WHERE ROWNUM = 1;

	DBMS_OUTPUT.PUT_LINE('1 DEPTNO  : ' || DEPT_REC1.DEPTNO || ' , DNAME : ' || DEPT_REC1.DNAME);
	
	L_DNAME := DEPT_REC1.DNAME;  --  := 할당문  우측의 값을 좌측에 넣겠다.
	
	DBMS_OUTPUT.PUT_LINE('2 DNAME : ' || L_DNAME);
	
	OPEN C1;
	FETCH C1 INTO DEPT_REC2;
	
	DBMS_OUTPUT.PUT_LINE('3 DEPTNO : ' || DEPT_REC2.DEPTNO || ' , DNAME : ' || DEPT_REC2.DNAME );
	
	CLOSE C1;
END 
;








