CREATE TABLE F_HTML (
	CD_ID VARCHAR2(50)
  , 	NAME VARCHAR2(50)
  , CMT VARCHAR2(100)
);

SELECT * FROM F_HTML;

INSERT INTO F_HTML 
VALUES
(
	'V_BG_COLOR2' , '¹è°æ»ö2' , 'PURPLE'
);



	V_STR VARCHAR2(1000);
	V_TOP_COLOR VARCHAR2(50);
	V_LAST_COLOR VARCHAR2(50);
	V_BG_COLOR1 VARCHAR2(50);
	V_BG_COLOR2 VARCHAR2(50);