CREATE VIEW WISE_USER.V_RK
AS 
;
SELECT MAX(DECODE(NO,1,VAL||','||RK)) COL1
        ,MAX(DECODE(NO,2,VAL||','||RK)) COL2
        ,MAX(DECODE(NO,3,VAL||','||RK)) COL3
FROM (
SELECT SEQ,NO,TA.VAL
           ,RANK() OVER( PARTITION BY SEQ ORDER BY ABS(TA.VAL - TB.VAL) ) RK
FROM (
SELECT SEQ,NO,DECODE(NO,1,COL1,2,COL2,3,COL3) VAL
FROM (
SELECT  1 SEQ,100 COL1,200 COL2, 300 COL3 FROM DUAL UNION ALL 
SELECT  2 SEQ,180 COL1,200 COL2, 300 COL3 FROM DUAL UNION ALL
SELECT  3 SEQ,220 COL1,200 COL2, 300 COL3 FROM DUAL
) A, COPY_T B
WHERE NO <=3 
) TA, 
( SELECT :VAR VAL
FROM DUAL )TB
)
GROUP BY SEQ
;